"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 20:47:49.027268
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cvss_version', sa.String(length=8), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('base_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('base_severity', sa.Enum('critical', 'high', 'medium', 'low', 'none', name='severity'), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('exploitability_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cpes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('epss_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kev', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('kev_added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kev_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nvd_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('items_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('primary_url', sa.Text(), nullable=False),
    sa.Column('stream', sa.Enum('main', 'elsewhere', name='stream'), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('vulnerability', 'breach', 'ransomware', 'advisory', 'research', 'news', name='category'), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('cvss', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'none', name='severity'), nullable=True),
    sa.Column('kev', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('patch_status', sa.Enum('patched', 'no_fix', 'workaround', 'unverified', name='patch_status'), server_default='unverified', nullable=False),
    sa.Column('patch_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_event_kind', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['cves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id')
    )
    op.create_index(op.f('ix_items_last_event_at'), 'items', ['last_event_at'], unique=False)
    op.create_index(op.f('ix_items_stream'), 'items', ['stream'], unique=False)
    op.create_index(op.f('ix_items_vendor_id'), 'items', ['vendor_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=True),
    sa.Column('stream', sa.Enum('main', 'elsewhere', name='stream'), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('health', sa.Enum('unknown', 'ok', 'failing', name='health'), server_default='unknown', nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_table('item_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_item_sources_item_id'), 'item_sources', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_sources_source_id'), 'item_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_sources_source_id'), table_name='item_sources')
    op.drop_index(op.f('ix_item_sources_item_id'), table_name='item_sources')
    op.drop_table('item_sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_items_vendor_id'), table_name='items')
    op.drop_index(op.f('ix_items_stream'), table_name='items')
    op.drop_index(op.f('ix_items_last_event_at'), table_name='items')
    op.drop_table('items')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('cves')
    for enum_name in ('severity', 'stream', 'category', 'patch_status', 'health'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
